In [1]:
import numpy as np

marks = np.array([78, 85, 90, 66, 88, 72, 95])
marks

array([78, 85, 90, 66, 88, 72, 95])

In [5]:
print("Mean:", marks.mean())
print("std:", marks.std())
print("Min:", marks.min())
print("Max:", marks.max())
print("Sum:", marks.sum())

Mean: 82.0
std: 9.636241116594315
Min: 66
Max: 95
Sum: 574


In [6]:
marks > 80

array([False,  True,  True, False,  True, False,  True])

In [7]:
marks[marks > 80]

array([85, 90, 88, 95])

In [8]:
marks[(marks > 80) & (marks < 95)]

array([85, 90, 88])

In [9]:
marks[marks < marks.mean()]

array([78, 66, 72])

In [11]:
print((marks > 80).sum())

4


In [12]:
import numpy as np

marks = np.array([45, 67, 89, 92, 76, 81])

high_scores = marks[marks > 80]

print(high_scores)

[89 92 81]


In [15]:
filtered = marks[(marks >= 70 ) & (marks <= 90)]
print(filtered)

[89 76 81]


In [16]:
marks[marks < 50] += 5
print(marks)

[50 67 89 92 76 81]


In [17]:
marks[marks < 60] = 60
print(marks)

[60 67 89 92 76 81]


In [18]:
print("count:", (marks > 80).sum())
print("Values:", marks[marks > 80])

count: 3
Values: [89 92 81]


In [30]:
import numpy as np

arr = np.array([12, 45, 67, 89, 23, 90, 100])

print("Numbers more than 50:", arr[arr > 50])

even_and_gt_50 = arr[(arr % 2 == 0) & (arr > 50)]

print("Extract numbers even AND > 50:", even_and_gt_50)

new_arr = arr.copy()
new_arr[new_arr <= 30] = 0

print("Original:", arr)
print("Modified:", new_arr)


Numbers more than 50: [ 67  89  90 100]
Extract numbers even AND > 50: [ 90 100]
Original: [ 12  45  67  89  23  90 100]
Modified: [  0  45  67  89   0  90 100]
