In [5]:
import numpy as np

arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr))
print(arr[0])      # first element
print(arr[1:4])    # from index 1 to 3
print(arr[:3])     # first 3 elements
print(arr[2:])     # from index 2 to end



[10 20 30 40 50]
<class 'numpy.ndarray'>
10
[20 30 40]
[10 20 30]
[30 40 50]


AttributeError: module 'numpy' has no attribute 'arrange'

In [27]:
matrix = np.arange(1, 26).reshape(5, 5)
print(matrix)

# Top-left 3x3
print(matrix[:3, :3])
print("*****")
print(matrix[2:,2:])
print("**$**")
print(matrix[1:4, 1:4])
print("**$**")
print(matrix[:, -1])
print("*****")
print(matrix[:, 1])
print("*****")
print(matrix[1, :])
print("*****")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
*****
[[13 14 15]
 [18 19 20]
 [23 24 25]]
**$**
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
**$**
[ 5 10 15 20 25]
*****
[ 2  7 12 17 22]
*****
[ 6  7  8  9 10]
*****


In [15]:
arr = np.arange(1,13)
print(arr)

matrix = arr.reshape(3,4)
print(matrix)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
matrix = np.arange(1, 10).reshape(3, 3)
print(matrix)

print(matrix + 10)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [17]:
weights = np.array([1,2,3])
print(matrix * weights)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [18]:
arr = np.arange(1,101)
matrix = arr.reshape(10, 10)

print(matrix + 5)

[[  6   7   8   9  10  11  12  13  14  15]
 [ 16  17  18  19  20  21  22  23  24  25]
 [ 26  27  28  29  30  31  32  33  34  35]
 [ 36  37  38  39  40  41  42  43  44  45]
 [ 46  47  48  49  50  51  52  53  54  55]
 [ 56  57  58  59  60  61  62  63  64  65]
 [ 66  67  68  69  70  71  72  73  74  75]
 [ 76  77  78  79  80  81  82  83  84  85]
 [ 86  87  88  89  90  91  92  93  94  95]
 [ 96  97  98  99 100 101 102 103 104 105]]


In [28]:
arr = np.arange(1,101)
matrix = arr.reshape(10, 10)

matrix_even = matrix.copy()

mask = matrix_even % 2 ==0

matrix_even[mask] = matrix_even[mask] * 2

print(matrix_even)
print(matrix)
print(matrix[3:6, 3:6])


[[  1   4   3   8   5  12   7  16   9  20]
 [ 11  24  13  28  15  32  17  36  19  40]
 [ 21  44  23  48  25  52  27  56  29  60]
 [ 31  64  33  68  35  72  37  76  39  80]
 [ 41  84  43  88  45  92  47  96  49 100]
 [ 51 104  53 108  55 112  57 116  59 120]
 [ 61 124  63 128  65 132  67 136  69 140]
 [ 71 144  73 148  75 152  77 156  79 160]
 [ 81 164  83 168  85 172  87 176  89 180]
 [ 91 184  93 188  95 192  97 196  99 200]]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[[34 35 36]
 [44 45 46]
 [54 55 56]]
